# Generated by Django 5.1.6 on 2025-06-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0010_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to='posts/images'),
        ),
    ]
